version: '3.9'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
